import Link from 'next/link'

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-gradient-to-br from-gray-50 via-primary-50/30 to-accent-50/30">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 sm:py-16">
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-primary-600 hover:text-primary-700 font-semibold mb-8 transition-colors"
        >
          <svg
            className="w-5 h-5"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M10 19l-7-7m0 0l7-7m-7 7h18"
            />
          </svg>
          Back to Home
        </Link>

        <div className="bg-white rounded-2xl shadow-xl p-8 sm:p-12 border-2 border-gray-100">
          <h1 className="text-4xl sm:text-5xl font-bold bg-gradient-to-r from-primary-600 via-accent-600 to-teal-600 bg-clip-text text-transparent mb-4">
            Privacy Policy for VoyZa
          </h1>
          <p className="text-gray-600 mb-12 text-lg">
            Effective Date: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
          </p>

          <div className="prose prose-lg max-w-none space-y-8">
            <p className="text-gray-700 leading-relaxed">
              VoyZa ("we", "our", or "us") respects your privacy and is committed to protecting your personal data. This Privacy Policy explains how information is collected, used, stored, and shared when you use the VoyZa mobile application ("App").
            </p>

            <section className="space-y-6">
              <h2 className="text-2xl font-bold text-gray-900 mt-12 mb-4">1. Information We Collect</h2>
              
              <h3 className="text-xl font-semibold text-gray-900 mt-6 mb-3">1.1 Information You Provide</h3>
              <p className="text-gray-700 leading-relaxed">
                Depending on how you use the App, we may collect:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-gray-700">
                <li>Email address (when you create an account or make a subscription purchase)</li>
                <li>User-generated content, including:
                  <ul className="list-disc pl-6 mt-2 space-y-1">
                    <li>Trips</li>
                    <li>Locations</li>
                    <li>Notes or metadata associated with trips and locations</li>
                  </ul>
                </li>
                <li>Account identifiers (user ID generated by our system)</li>
              </ul>
              <p className="text-gray-700 leading-relaxed">
                Anonymous users are not required to provide personal information.
              </p>

              <h3 className="text-xl font-semibold text-gray-900 mt-6 mb-3">1.2 Location Data</h3>
              <ul className="list-disc pl-6 space-y-2 text-gray-700">
                <li>The App allows users to add and manage locations manually</li>
                <li>VoyZa does not track your real-time GPS location in the background</li>
                <li>Any location data you add is:
                  <ul className="list-disc pl-6 mt-2 space-y-1">
                    <li>Stored locally on your device (anonymous users), or</li>
                    <li>Stored securely in our database (authenticated users)</li>
                  </ul>
                </li>
              </ul>

              <h3 className="text-xl font-semibold text-gray-900 mt-6 mb-3">1.3 Subscription & Purchase Information</h3>
              <p className="text-gray-700 leading-relaxed">
                VoyZa uses third-party services (such as RevenueCat and app store providers) to manage subscriptions.
              </p>
              <p className="text-gray-700 leading-relaxed">
                We may receive:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-gray-700">
                <li>Subscription status (active, expired, restored)</li>
                <li>Purchase history metadata (not credit card numbers)</li>
              </ul>
              <p className="text-gray-700 leading-relaxed font-semibold mt-4">
                We do NOT collect or store:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-gray-700">
                <li>Credit card numbers</li>
                <li>Bank account details</li>
                <li>Payment credentials</li>
              </ul>
              <p className="text-gray-700 leading-relaxed">
                All payments are handled securely by Apple App Store or Google Play Store.
              </p>

              <h3 className="text-xl font-semibold text-gray-900 mt-6 mb-3">1.4 Automatically Collected Information</h3>
              <p className="text-gray-700 leading-relaxed">
                We may collect limited technical data such as:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-gray-700">
                <li>Device identifiers</li>
                <li>App version</li>
                <li>Crash logs and diagnostics</li>
              </ul>
              <p className="text-gray-700 leading-relaxed">
                This data is used solely for:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-gray-700">
                <li>App stability</li>
                <li>Bug fixes</li>
                <li>Performance improvements</li>
              </ul>
            </section>

            <section className="space-y-6">
              <h2 className="text-2xl font-bold text-gray-900 mt-12 mb-4">2. How We Use Your Data</h2>
              <p className="text-gray-700 leading-relaxed">
                We use your information to:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-gray-700">
                <li>Provide core app functionality (trip planning, location management)</li>
                <li>Sync data across devices for logged-in users</li>
                <li>Manage subscriptions and entitlement access</li>
                <li>Restore purchases</li>
                <li>Improve app performance and reliability</li>
                <li>Communicate essential account-related information</li>
              </ul>
              <p className="text-gray-700 leading-relaxed font-semibold mt-4">
                We do not use your data for:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-gray-700">
                <li>In-app advertising</li>
                <li>Selling personal data</li>
                <li>Third-party marketing</li>
              </ul>
            </section>

            <section className="space-y-6">
              <h2 className="text-2xl font-bold text-gray-900 mt-12 mb-4">3. Anonymous Usage</h2>
              <p className="text-gray-700 leading-relaxed">
                VoyZa supports anonymous usage:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-gray-700">
                <li>Data is stored locally on your device</li>
                <li>No personal information is collected</li>
                <li>If you later sign in, you may choose whether to sync your local data to your account</li>
              </ul>
              <p className="text-gray-700 leading-relaxed">
                Anonymous data is never uploaded without your explicit action.
              </p>
            </section>

            <section className="space-y-6">
              <h2 className="text-2xl font-bold text-gray-900 mt-12 mb-4">4. Data Sharing</h2>
              <p className="text-gray-700 leading-relaxed">
                We only share data with trusted third-party services necessary to operate the App, such as:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-gray-700">
                <li>Authentication providers</li>
                <li>Database and cloud infrastructure providers</li>
                <li>Subscription management platforms (e.g., RevenueCat)</li>
              </ul>
              <p className="text-gray-700 leading-relaxed">
                Data is shared only for app functionality, security, and compliance purposes.
              </p>
              <p className="text-gray-700 leading-relaxed font-semibold">
                We do not sell or rent your personal data.
              </p>
            </section>

            <section className="space-y-6">
              <h2 className="text-2xl font-bold text-gray-900 mt-12 mb-4">5. Data Security</h2>
              <p className="text-gray-700 leading-relaxed">
                We implement reasonable technical and organizational measures to protect your data, including:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-gray-700">
                <li>Encryption in transit (HTTPS)</li>
                <li>Secure access controls</li>
                <li>Restricted internal access</li>
              </ul>
              <p className="text-gray-700 leading-relaxed">
                No system is 100% secure, but we take data protection seriously.
              </p>
            </section>

            <section className="space-y-6">
              <h2 className="text-2xl font-bold text-gray-900 mt-12 mb-4">6. Data Retention</h2>
              <p className="text-gray-700 leading-relaxed">
                We retain your data only as long as necessary to:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-gray-700">
                <li>Provide the App's services</li>
                <li>Comply with legal obligations</li>
                <li>Resolve disputes</li>
              </ul>
              <p className="text-gray-700 leading-relaxed">
                You may request deletion at any time.
              </p>
            </section>

            <section className="space-y-6">
              <h2 className="text-2xl font-bold text-gray-900 mt-12 mb-4">7. Account & Data Deletion</h2>
              <p className="text-gray-700 leading-relaxed">
                You can delete your account and associated data by:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-gray-700">
                <li>Using the in-app account deletion feature (if available), or</li>
                <li>Contacting us at: hengsamkok76@gmail.com</li>
              </ul>
              <p className="text-gray-700 leading-relaxed">
                Upon deletion:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-gray-700">
                <li>Your personal data and trips stored on our servers will be permanently removed</li>
                <li>Subscription records may be retained as required by law</li>
              </ul>
            </section>

            <section className="space-y-6">
              <h2 className="text-2xl font-bold text-gray-900 mt-12 mb-4">8. Children's Privacy</h2>
              <p className="text-gray-700 leading-relaxed">
                VoyZa is not intended for users under the age of 13.
              </p>
              <p className="text-gray-700 leading-relaxed">
                We do not knowingly collect data from children.
              </p>
            </section>

            <section className="space-y-6">
              <h2 className="text-2xl font-bold text-gray-900 mt-12 mb-4">9. Your Rights</h2>
              <p className="text-gray-700 leading-relaxed">
                Depending on your jurisdiction, you may have the right to:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-gray-700">
                <li>Access your data</li>
                <li>Correct inaccurate data</li>
                <li>Request deletion</li>
                <li>Withdraw consent where applicable</li>
              </ul>
              <p className="text-gray-700 leading-relaxed">
                Contact us to exercise these rights.
              </p>
            </section>

            <section className="space-y-6">
              <h2 className="text-2xl font-bold text-gray-900 mt-12 mb-4">10. Changes to This Policy</h2>
              <p className="text-gray-700 leading-relaxed">
                We may update this Privacy Policy from time to time.
              </p>
              <p className="text-gray-700 leading-relaxed">
                Changes will be posted on this page with an updated effective date.
              </p>
            </section>

            <section className="space-y-6">
              <h2 className="text-2xl font-bold text-gray-900 mt-12 mb-4">11. Contact Us</h2>
              <p className="text-gray-700 leading-relaxed">
                If you have any questions about this Privacy Policy, contact us at:
              </p>
              <div className="bg-gradient-to-r from-primary-50 to-accent-50 rounded-xl p-6 border-2 border-primary-200 mt-4">
                <p className="text-gray-900 font-semibold mb-2">Email:</p>
                <a
                  href="mailto:hengsamkok76@gmail.com"
                  className="text-primary-600 hover:text-primary-700 font-medium underline"
                >
                  hengsamkok76@gmail.com
                </a>
                <p className="text-gray-900 font-semibold mt-4 mb-2">App Name:</p>
                <p className="text-gray-700">VoyZa</p>
              </div>
            </section>
          </div>

          <div className="mt-12 pt-8 border-t border-gray-200">
            <Link
              href="/"
              className="inline-flex items-center gap-2 text-primary-600 hover:text-primary-700 font-semibold transition-colors"
            >
              <svg
                className="w-5 h-5"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M10 19l-7-7m0 0l7-7m-7 7h18"
                />
              </svg>
              Back to Home
            </Link>
          </div>
        </div>
      </div>
    </main>
  )
}
